# Generated by Django 5.0.3 on 2024-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='orders',
        ),
        migrations.AddField(
            model_name='products',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='kkk', to='foodapp.orders'),
        ),
    ]
