# Generated by Django 5.0.3 on 2024-03-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_remove_products_orders_products_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='orders',
            field=models.ManyToManyField(related_name='kkk', to='foodapp.orders'),
        ),
    ]
